### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by marcolino** [Chris-Johnston/BinaryKeyboard#3]
Just this simple question: which is the goal of this project?

**Comment by dtwilliamson** [comment]
Because computers use binary, duh!

**Comment by Chris-Johnston** [comment]
I'm not sure this counts as a valid issue (unless you want me to write this somewhere). 

My goal was to make something completely ridiculous after making an Ergodox a few months ago. People have already made binary keyboards, but I wanted to make one myself as well as w/ backlighting and a screen because I could. Added bonus was finally getting around to using a CNC machine and messing with Eagle.

Good enough goal?
